version: '3'

services:
  web:
#    image: sandbox-docker.artifactory.site.dukascopy.com/php/php-73-dev-nginx:latest
    image: bitnami/symfony:latest
    ports:
      - "8000:8000"
    working_dir: /app
    hostname: weather-api
    environment:
      HTTP_PROXY: "127.0.0.1:3128"
      HTTPS_PROXY: "127.0.0.1:3128"
      http_proxy: "127.0.0.1:3128"
      https_proxy: "127.0.0.1:3128"
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ~/.composer/auth.json:/tmp/auth.json
      - ~/.composer/config.json:/tmp/config.json
