version: '3'

services:
  web:
    image: bitnami/symfony:latest
    ports:
      - "8000:8000"
    working_dir: /app
    hostname: weather-api
    environment:
# when localhost proxy used
#      HTTP_PROXY: "host.docker.internal:3128"
#      HTTPS_PROXY: "host.docker.internal:3128"
#      http_proxy: "host.docker.internal:3128"
#      https_proxy: "host.docker.internal:3128"
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - .:/app
#      - ~/.composer/auth.json:/tmp/auth.json
#      - ~/.composer/config.json:/tmp/config.json
